TRY-HACK!! rust: fix map_wc related build failure
Use set_map_wc(map_wc) instead of assigning the bool to map_wc.

Fixes

error[E0615]: attempted to take value of method `map_wc` on type `drm_gem_shmem_object`
   --> /home/nst/git/linux-asahi/rust/kernel/drm/gem/shmem.rs:217:38
    |
217 |         unsafe { (*self.mut_shmem()).map_wc = map_wc };
    |                                      ^^^^^^ method, not a field
    |
    = help: methods are immutable and cannot be assigned to