ASoC: CS35L45: fix build errors related to REGMAP_IRQ
Select REGMAP_IRQ when this driver is to be built. Fixes

    ERROR: modpost: "regmap_irq_get_virq" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
    ERROR: modpost: "devm_regmap_add_irq_chip" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!

when REGMAP_IRQ isn't autoselected via some other drivers or means.

Fixes: 6085f9e6dc19 ("ASoC: cs35l45: IRQ support")