partially apply "rust: 1.70 compat hack"
Needed as the impl_trait_in_assoc_type feature is required to build the
Asahi GPU driver.

Fixes:

    error[E0658]: `impl Trait` in associated types is unstable
       --> /home/nst/git/linux-asahi/drivers/gpu/drm/asahi/gem.rs:240:24
        |
    240 |     type Initializer = impl PinInit<Self, Error>;
        |                        ^^^^^^^^^^^^^^^^^^^^^^^^^
        |
        = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
        = help: add `#![feature(impl_trait_in_assoc_type)]` to the crate attributes to enable